title: "Using Polars in Rust for high-performance data analysis"
short: "In this post, we'll build a basic data analysis pipeline using Rust and Polars."
date: 05.11.2024
tags:
    - rust
    - polars
    - data
    - analysis
canonical: https://blog.logrocket.com/using-polars-rust-high-performance-data-analysis/
